export const themes = {
  horizon: {
    primary: "#2D6A4F",
    secondary: "#D4A843",
    bg: "#FAF9F6",
    surface: "#FFFFFF",
    text: "#1A1A2E",
    textMuted: "#6B7280",
    danger: "#DC3545",
    success: "#2D6A4F",
    radius: "12px",
    radiusInput: "8px",
    fontSize: "16px",
    fontFamily: "'Inter', 'Source Sans Pro', sans-serif",
    fontMono: "'SF Mono', 'Consolas', monospace",
    spacing: "24px",
    spacingCompact: "16px",
    isDark: false,
  },
  velocity: {
    primary: "#3B82F6",
    secondary: "#10B981",
    bg: "#0F172A",
    surface: "#1E293B",
    text: "#F8FAFC",
    textMuted: "#94A3B8",
    danger: "#EF4444",
    success: "#10B981",
    radius: "8px",
    radiusInput: "6px",
    fontSize: "24px",
    fontFamily: "'Inter', sans-serif",
    fontMono: "'JetBrains Mono', 'SF Mono', monospace",
    spacing: "16px",
    spacingCompact: "8px",
    isDark: true,
  },
} as const;

export type ThemeTokens = (typeof themes)[keyof typeof themes];
